---
required_packages:
  - sudo
  - python-pip
  - python-virtualenv
  - git
  # Used to verify GPG signatures for mirrored packages
  - gnupg
  - iptables
  # Word List dictionary used by several roles to generate random data
  - "{{ package_name_words }}"
  - openssl
  - openvpn
